### ISSUE TITLE
Don't download Uno.ProjectTemplates.Dotnet on build

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#105]
https://github.com/unoplatform/uno.templates/blob/f236d58d1651c6c56e8c23008f9f05867a5c217d/src/Uno.Templates/Uno.Templates.csproj#L85

The package is no longer updated and will remain on 4.8.0-dev.792. I think its contents should be part of the repository directly without the additional build logic to download and extract it.

**Comment by Youssef1313** [comment]
cc @jeromelaban @dansiegel @nickrandolph

**Comment by nickrandolph** [comment]
@jeromelaban I thought the point was to have the existing template close to Uno so they could be used for validating Uno builds. Happy to move them if this isn't needed

**Comment by Youssef1313** [comment]
There are two parts here:

### unoplatform/uno.templates repository

Uno.ProjectTemplates.Dotnet will never release a new version, so in this repo, we always download the same thing, which is kinda rundant.

### unoplatform/uno repository

On the unoplatform/uno repo, I was thinking we want to keep building them to make sure the build isn't broken. What we can do is remove Uno.ProjectTemplates.Dotnet and instead install Uno.Templates as part of the CI run, then adjust referenced packages to use ones from unoplatform/uno PR artifacts and build that.
