### ISSUE TITLE
Loading fonts fails on Wasm when the browser uri is altered (e.g, navigation)

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#132]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/31348972/ad7fa7fd-aa80-4eb4-bfa3-c3657fe1ebe6)

Note: the font is packaged correctly, but the url isn't supposed to have "/Main" (which comes from navigation routes)

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
Let's track it here then.

**Comment by lukeblevins** [comment]
@Youssef1313 Opened an issue here: https://github.com/unoplatform/uno.extensions/issues/1472
