### ISSUE TITLE
[Discussion] Quick Debug Cycle for Developers

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.templates#145]
## Background

Since moving to a multi-targeted class library every time a change is made to an uno app, every target in the class library is built, significantly increasing the time to build and launch an app as part of the debugging cycle.

Despite multi-targeting being around for quite sometime, there's no support within Visual Studio for only building a single tfm in a class library, with the exception of the single-project structure used by Maui.

The purpose of this discussion is to find a guidance that will let developers build a single target, whilst not adding significantly to the overall complexity of an uno application

## Option 1: props file

This strategy is used by a number of the uno repositories and is demonstrated in this [draft pr](https://github.com/unoplatform/uno.templates/pull/142).

## Option 2: bat files

This strategy isn't much different from Option 1 in that it replaces the TargetFrameworks property based on an override property and is demonstrated in this [draft pr](https://github.com/unoplatform/uno.templates/pull/141). However instead of specifying it in a props file, it's set as a command line environment variable by a bat script. The script also deletes the bin/obj, performs a restore and then launches the appropriate solution filter.

## Option 3: dotnet tool

This option would involve the creation of a dotnet tool (eg uno-debug) that would carry out the same functions as Option 2 but without the additional bat and slnf files.

**Comment by dansiegel** [comment]
closed via #142
