### ISSUE TITLE
DataContracts is still created in the solution

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno.templates#148]
## Current behavior

Creating a project from the template wizard, with server unchecked, DataContracts is still created in the solution
![image](https://github.com/unoplatform/uno.templates/assets/7770915/05c2bb7e-e91b-4121-b8cf-b2990dc730c3)

## Expected behavior

DataContracts should not be created in the solution
## How to reproduce it (as minimally and precisely as possible)

Create a new project with the template
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@carlh98 this would most likely be because you included the http option - this includes a sample where the contract is included in the datacontract project
