### ISSUE TITLE
Add `VisibleBoundsPadding` to default template

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno.templates#152]
## What would you like to be added:
Set [VisibleBoundsPadding](https://platform.uno/docs/articles/features/VisibleBoundsPadding.html) in the default Uno template

## Why is this needed:
Apps don't display properly on iPhones and notched Android devices without it

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dansiegel** [comment]
The Recommended preset already uses SafeArea, and the default Blank preset MainPage has it's content centered so this really should no longer be an issue. Please feel free to reopen if we need to revisit this again.
