### ISSUE TITLE
Creating Uno app with dashes in name won't compile

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno.templates#156]
## Current behavior
If you try to create a Uno App with dashes in its name (or port existing UWP app with such name), you'll get the following problems:
* The `.Shared` project won't be referenced by the UWP head, but once linked properly, will build & run as expected.
* As soon you're adding a resource into `App.xaml`, you'll get compilation errors on all platforms except on UWP.

## Expected behavior
* Template should link shared project properly.
* Everything should compile & run as on UWP.

## How to reproduce it (as minimally and precisely as possible)
1. Create a Uno project named `App-With-Dashes`
2. Launch compilation  -- it will fail because of missing shared projects
3. Redo the Shared project references for all heads
4. Compile - only UWP head will compile & run.
6. Other (Droid, iOS, macOS,Wasm) will fail with the following error:
   ```
   error CS0116: A namespace cannot directly contain members such as fields or methods
   ```
   Source of error `BindableMetadata.g.cs`: (dashes in namespace)
   ![image](https://user-images.githubusercontent.com/4174207/82934739-f7694b00-9f59-11ea-99b1-dc64ca0c97b9.png)

## Explanation
* In _dotnet_, it's acceptable to have dashes for an assembly name. Many Microsoft samples are doing this.

## Environment

Nuget Package: 2.4+

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Windows
- [ ] Build tasks
- [X] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

**Comment by mrlacey** [comment]
This is still around, and even worse than that is the new wizard explicitly warning, when other invalid characters are used, that dashes are supported. 😭 😞 

![To avoid compilation issues limit project name to alphanumeric characters, dashes and underscores.](https://github.com/unoplatform/uno.templates/assets/189547/ea92fc7f-f1b8-43fc-ae2b-8de85bf546af)

**Comment by dansiegel** [comment]
closing this as a duplicate of #94

**Comment by KWodarczyk** [comment]
this should be reopen still not possible to create uno app with name that contains dashes e.g uno-test-app and also if underscore is used instead e.g uno_test_app the app is create but can't be build  

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.uno_test_app' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.uno_test_app' failed to parse.	uno_test_app

**Comment by dansiegel** [comment]
@KWodarczyk feel free to open an issue on the main Uno repository but from a templates perspective there is nothing that we can do to allow this. There are too many processes that are outside of our control that will cause your project to fail to build/run which is why this is prevented from a template perspective.

**Comment by KWodarczyk** [comment]
But underscore is not prevented so you can create the app but it fails to build.
