### ISSUE TITLE
Providing multiple values via pipe

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#163]
## What would you like to be added:

Currently, providing option like `--platforms` with multiple options requires using it multiple times, eg.:

```
dotnet new unoapp --platforms=gtk --platforms=android
```

Even though `--help` even states that the default is: 

![image](https://github.com/unoplatform/uno.templates/assets/1075116/a8b7d6fd-9f78-4e51-a2ee-b2c637f1aad8)

## Why is this needed:

Providing the values as:

```
dotnet new unoapp --platforms=gtk|android
```

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by nickrandolph** [comment]
This is a dotnet new "feature" and not something we can do anything about.
