### ISSUE TITLE
Why is the splash screen background blue 👀 ?

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#175]
## What would you like to be added:

The current splash screen background color is blue and quite closely resembles Windows Blue Screen of Death. In addition, it does not play well with our logo at all in terms of contrast. Why does the splash screen not use the themed background color - e.g. light/dark background, to be less disruptive against the rest of the application? Theme-aware splash screen is definitely supported on WebAssembly ([see here](https://platform.uno/docs/articles/splash-screen.html?tabs=tabid-vswin#step-5---webassembly)), and it should probably be possible to implement it on other targets too.

![image](https://github.com/unoplatform/uno.templates/assets/1075116/3340e7ed-6677-4865-8093-7646cd06a96f)

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

**Comment by nickrandolph** [comment]
I could be wrong but I think this uses the non-theme background color: splashScreenColor

**Comment by MartinZikmund** [comment]
Yes, then that's something that definitely needs to be addressed on the Resizetizer side... Actually when I changed the background color in `base.props`, the logo background remained the BSOD blue 😕

**Comment by MartinZikmund** [comment]
And before Resizetizer is improved, I would still vote to switching to white background, so the logo looks better

**Comment by MartinZikmund** [comment]
Ping on this, can we still switch to white background for 4.10 or is it too much effort? @agneszitte
