### ISSUE TITLE
Remove unnecessary packages from platform heads

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno.templates#177]
## What would you like to be added:
Review the generated templates and remove all redundant packages.

## Why is this needed:
Some of the generated templates' platform heads contain installed packages which are there for legacy purposes. Some are enough to be installed only on the main head.

In addition, some packages would be referenced there via a dependency and don't necessarily need to be referenced directly.
There should be as few packages as possible, especially in the blank template.

## For which Platform:

- All

**Comment by dansiegel** [comment]
Closed via #585
