### ISSUE TITLE
net8 requires RuntimeIdentifiers to be specified for net80.-windows

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.templates#183]
<h1>Problem</h1>

I`am trying to build my shared UnoApplication project:
![image](https://github.com/unoplatform/uno/assets/69314237/f0f45f59-fdc1-4a58-adb8-0c0f5dd611e5)

But at the output I have the following message:
```
1>C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(479,5): error NETSDK1082: There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm'.
1>C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(479,5): error NETSDK1082: There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm-aot'.
```

<h1>What I already tried to do</h1>

<h3>Uno-check</h3>

I started uno-check (1.13.0.0)
```
uno-check --preview-major
```

There I have the following message:
![image](https://github.com/unoplatform/uno/assets/69314237/93c1fd6d-60a6-405a-b083-a8d153b3b2f1)

But uno-check not fixing this problem.

<h4>Option info</h4>

My ```C:\Windows\System32\global.json```
```JSON
{
  "sdk": {
    "version": "8.0.100-preview.6.23330.14",
    "allowPrerelease": true
  }
}
```
My ```dotnet --list-sdks```
```
7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
8.0.100-preview.2.23157.25 [C:\Program Files\dotnet\sdk]
8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
```
<h3>RuntimeIdentifiers</h3>
I added the following lines to my .csproj file

```XML
<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041'">
  <RuntimeIdentifiers>win10-arm;win10-arm-aot;</RuntimeIdentifiers>    
</PropertyGroup>
```
It didn`t helps me.

<h1>Info</h1>

Visual Studio Community 2022 17.7.0 Preview 5.0
Windows 11
Uno.WinUI 4.9.17

_Originally posted by @limeniye in https://github.com/unoplatform/uno/discussions/13028_

**Comment by jeromelaban** [comment]
Fixing it requires adding the missing property:
https://github.com/unoplatform/uno/discussions/13028#discussioncomment-6565354

**Comment by limeniye** [comment]
@jeromelaban , is it hard task?
Can I try to fix it by myself to create a first PR for Uno Platform?))

Because I see that its will work only if I will use MsalAuth

https://github.com/unoplatform/uno.templates/blob/7242d1416569455c818107a65c8f6e5ce8bd0e22/src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj#L202

And I already tested It:

![image](https://github.com/unoplatform/uno.templates/assets/69314237/8dbaa5f2-d673-4846-bef5-dc914a32fb6f)

- With Msal auth another errors;
- With Msal auth I dont see the problem with net8.0-windows....

**Comment by jeromelaban** [comment]
The errors you are seeing will be fixed by the upcoming release of uno (https://github.com/unoplatform/uno/pull/12880), but if you upgrade to the latest 4.10-dev.xx builds it should work,

As for implementing the change, @dansiegel can help :)

**Comment by limeniye** [comment]
I have been tried to update all Uno.xxx packages to dev versions
It didn`t gives me expected result.

Currently, I tried to do the same with 4.10.dev.xx (before I tried with 5.xxx-dev).

![image](https://github.com/unoplatform/uno.templates/assets/69314237/da77ef36-96f0-4521-8cb3-c751d32d1f88)

But didn't helps me.
