### ISSUE TITLE
Enable Embedding Validations

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.templates#192]
These should be enabled

_Originally posted by @nickrandolph in https://github.com/unoplatform/uno.templates/pull/185#discussion_r1282732125_

**Comment by Youssef1313** [comment]
Found a strange behavior of ResolvePackageAssets. Opened https://developercommunity.visualstudio.com/t/NET-SDK-not-passing-reference-to-Csc-pr/10430256 to try to get an explanation of why this behavior happens.

**Comment by nickrandolph** [comment]
This is fixed
