### ISSUE TITLE
`.vsconfig` file should take into account the wizard settings

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno.templates#227]
## What would you like to be added:
Some users are using VS 17.2 and use the Wizard to disable mobile solutions. 
![image](https://user-images.githubusercontent.com/3002068/180825463-c85dc4f0-af00-44c1-b48f-ce26dc910eba.png)
That being said, VS still offers to install missing things. 
![image](https://user-images.githubusercontent.com/3002068/180825901-2d3ecc21-aaa9-4708-b056-f9347bcfaa41.png)
From this suggestion to generate .vsconfig depending on chosen targets(for the foreseeable future when mobile development stabilizes)

When you click on Install, an empty window will appear.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by limeniye** [comment]
@dansiegel, @jeromelaban 
Good day!

I already installed Visual Studio 17.2 But I have the following two problems:
 - The Uno create project wizard is new, but in issue its an old design. How can I test it with old wizard?
- When I'am trying to create the new Uno application in VS 17.2 -- the project is empty with the following message:

![empty_solution.png](https://github.com/unoplatform/uno.templates/assets/69314237/4a5af39b-d446-4031-9587-a7eb94a968a4)

**Comment by jeromelaban** [comment]
@limeniye thanks for taking a look at this issue! The Wizard is currently closed source (The screenshot above is from the legacy wizard that has been removed), so you won't be able to validate your changes this way. 

The templates that are part of this repo can be built and tested from the command line using `dotnet new install [path_to_your_build_output]`.

**Comment by limeniye** [comment]
@jeromelaban, I found this topic: https://platform.uno/docs/articles/get-started-dotnet-new.html?tabs=net7%2Cwindows
This command allows me to download the latest version: ```dotnet new install Uno.Templates```

![image](https://github.com/unoplatform/uno.templates/assets/69314237/133862e3-c2ee-4936-b6ad-7d26ac3a6462)

But I need something like this: ```dotnet new install Uno.Templates:0.2```.
