### ISSUE TITLE
`Binding` to `ListView.ItemsSource` not working while `x:Bind` works

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#228]
### Current behavior

When using `Binding`:

![image](https://github.com/unoplatform/uno/assets/31348972/7921a6e3-de37-441b-96d7-05afbfd4fc0a)

When using `x:Bind`:

![image](https://github.com/unoplatform/uno/assets/31348972/5dadc9a4-e80a-4e5b-a862-15799b209611)

### Expected behavior

Both `Binding` and `x:Bind` are expected to work.

### How to reproduce it (as minimally and precisely as possible)

https://github.com/Youssef1313/issues10285

### Works on UWP/WinUI

None

**Comment by nickrandolph** [comment]
Replacing this issue with https://github.com/unoplatform/uno.templates/issues/288
