### ISSUE TITLE
App created with unoapp template won't compile with Visual Studio Version 17.4.0 (stable)

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.templates#234]
### Current behavior

Create new app using dotnet new template unoapp
Open in Visual Studio
Won't compile as looks for Android 31.0 (net6.0-android)<-- this is removed by default in VS 17.4.0

### Expected behavior

Application should compile after created using template

**Comment by ADD-David-Antolin** [comment]
It is not relevant to us because we have already migrated to .NET 7, but the issue will still happen for .NET 6. 
Maybe uno-check could download Android SDK 31 while .NET 6 is supported for Uno Platform development.

**Comment by jeromelaban** [comment]
Thanks. In all cases, .NET 6 is now out of support from Microsoft, so it's now best to move to .NET 7 or later.
