### ISSUE TITLE
Should the template be disabling Uno0001?

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#26]
https://github.com/unoplatform/uno.templates/blob/da17fbe452537c56a583c6788f97f7a48e3ccef7/src/Uno.Templates/content/unoapp/Directory.Build.props#L18

This is our own analyzer. If we disable it for new projects, then why do we keep the analyzer at all?

I think either it should be enabled, removed completely, or make any necessary tweaks if the analyzer is annoying for a particular case that it could handle better.

It doesn't feel right that we have an analyzer and then disable it completely right away for new projects.

**Comment by dansiegel** [comment]
Not actually sure why it's there... my guess it's its an oversight
