### ISSUE TITLE
newly created `unoapp` fails to build

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.templates#312]
## Current behavior
newly created `unoapp` fails to build with:
```
1>D:\code\uno\tests\UnoAppTemplateCrash\UnoAppTemplateCrash.DataContracts\Serialization\WeatherForecastContext.cs(22,22,22,44): error CS0534: 'WeatherForecastContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
1>D:\code\uno\tests\UnoAppTemplateCrash\UnoAppTemplateCrash.DataContracts\Serialization\WeatherForecastContext.cs(22,22,22,44): error CS0534: 'WeatherForecastContext' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get'
1>Done building project "UnoAppTemplateCrash.DataContracts.csproj" -- FAILED.
```

## Expected behavior
should work

## How to reproduce it (as minimally and precisely as possible)
- `dotnet new unoapp -n AsdAsd`
- open solution in visual studio
- attempt to build windows or skia.gtk head

## Environment
Package Version(s): uno.templates::5.0.0-dev.486
Affected platform(s):

- [x] Skia.GTK
- [x] Windows
- [ ] didnt test the rest of platforms

Visual Studio: 2022
Relevant plugins: n/a

## Anything else we need to know?
binlog: [UnoAppTemplateCrash.DataContracts_Debug_AnyCPU_Build_2023-09-21T14_53_00.3443417-04_00.zip](https://github.com/unoplatform/uno.templates/files/12690691/UnoAppTemplateCrash.DataContracts_Debug_AnyCPU_Build_2023-09-21T14_53_00.3443417-04_00.zip)
solution: [UnoAppTemplateCrash.zip](https://github.com/unoplatform/uno.templates/files/12690694/UnoAppTemplateCrash.zip)

**Comment by nickrandolph** [comment]
@Xiaoy312 can you try the latest template please - I'm not seeing any issues currently

**Comment by nickrandolph** [comment]
I've tested with the instructions on the template from this PR https://github.com/unoplatform/uno.templates/pull/353
And both Windows and GTK build and run fine, so closing this
