### ISSUE TITLE
App Icon SVG should be called `appiconfg.svg`, not `appconfig.svg`

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.templates#342]
In the Base.csproj, we are including an `appconfig.svg` which is sort of confusing since it should be used as the `ForegroundFile` and has nothing to do with "config".

 `<UnoIcon Include="$(MSBuildThisFileDirectory)Icons\iconapp.svg" ForegroundFile="$(MSBuildThisFileDirectory)Icons\appconfig.svg" ForegroundScale="0.65" Color="#00000000" />`

Looking at the[ MAUI documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android) for app icons, they are calling it `appiconfg.svg`

`<MauiIcon Include="Resources\AppIcon\appicon.png" ForegroundFile="Resources\AppIcon\appiconfg.svg" TintColor="Yellow" />`

**Comment by nickrandolph** [comment]
Even that name isn't that clear. Perhaps appicon_foreground.svg or just appicon.fg
