### ISSUE TITLE
Solution templates create no project

### ISSUE THREAD

**Issue by HO-COOH** [unoplatform/uno.templates#351]
## Current behavior
No project was created.

## Expected behavior
Project created.

## How to reproduce it (as minimally and precisely as possible)
Create a new solution with .net6 UWP project.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [x] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

2022. You should update this issue template :)

Relevant plugins:
Nope.

**Comment by jeromelaban** [comment]
Thanks for the report. 

Could you take a screenshot of the option you chose, as well as a screenshot of the resulting solution?

**Comment by HO-COOH** [comment]
A fresh install of uno with `dotnet uno check`, with everything fixed.

https://github.com/unoplatform/uno.templates/assets/42881734/bc3ce7ea-f4b4-4501-ae88-f1d987b14c2c

**Comment by nickrandolph** [comment]
@HO-COOH we've just published new versions of the vsix for Visual Studio. Can you try it out and confirm whether you're still having this issue

**Comment by HO-COOH** [comment]
Thanks, that solves this issue
