### ISSUE TITLE
WinAppSDK crash on startup when using most Material styles

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.templates#361]
Installing latest dev templates with `dotnet new install uno.templates::5.0.0-dev.486` and running `dotnet new unoapp -o MyTestApp` results in a crash on startup when running the Windows head:

![1fd461f4-747a-420c-9aed-371ccf49768d](https://github.com/unoplatform/uno.templates/assets/4793020/dfe8999b-217e-4b9f-b8f9-0865b4911cd8)

With latest VS Stable and VS Preview

App starts fine if I use `dotnet new unoapp -preset=blank -o MyTestApp`

**Comment by nickrandolph** [comment]
Closing this as it's been resolved by removing trimming
