### ISSUE TITLE
dotnet restore fails on Mac when Windows target exists

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno.templates#372]
## Current behavior

After creating a default project on Mac and running dotnet restore the restore fails because a Windows project exists.

```
PS /Users/dansiegel/repos/Uno/uno.templates/src/Uno.Templates> dotnet new unoapp -skip -o UnoApp1 -markup csharp
The template "Uno Platform App" was created successfully.

PS /Users/dansiegel/repos/Uno/uno.templates/src/Uno.Templates> cd ./UnoApp1/          
PS /Users/dansiegel/repos/Uno/uno.templates/src/Uno.Templates/UnoApp1> dotnet restore                                   
  Determining projects to restore...
/usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/Users/dansiegel/repos/Uno/uno.templates/src/Uno.Templates/UnoApp1/UnoApp1.Windows/UnoApp1.Windows.csproj]
```

## Expected behavior

`dotnet restore` should be able to restore the projects or at least ignore Windows

## How to reproduce it (as minimally and precisely as possible)

```
dotnet new unoapp --skip
dotnet restore  
```

**Comment by nickrandolph** [comment]
We used to have a .slnf file for the mac so that you could do a restore just on projects for the mac. This was removed because we don't support VS for mac any more and VS code ignores them.
I'm reluctant to set EnableWindowsTargeting to true but maybe only option

**Comment by spouliot** [comment]
`EnableWindowsTargeting` was added to templates for VS Code support (outside of Windows).
https://github.com/unoplatform/uno.templates/pull/494
