### ISSUE TITLE
CS1591 should not be disabled

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#38]
https://github.com/unoplatform/uno.templates/blob/9e09f5861948060dfbd9c11c5f24e7fc6ef115e2/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Server/MyExtensionsApp.1.Server.csproj#L6

https://github.com/unoplatform/uno.templates/blob/9e09f5861948060dfbd9c11c5f24e7fc6ef115e2/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.DataContracts/MyExtensionsApp.1.DataContracts.csproj#L6

We should do one of the following:

- Not setting `GenerateDocumentationFile` to true, and remove the NoWarn of CS1591
- Keeping `GenerateDocumentationFile` as true, *address* the warnings, and remove the NoWarn of CS1591

Compiler warnings shouldn't be suppressed in templates unless absolutely necessary.

It's best if we can get rid of **all** the NoWarn, but for now at least let's remove CS1591.

**Comment by dansiegel** [comment]
No this is very purposeful here. You shouldn't get warning for missing xml docs if you don't want to use them, and we do require `<GenerateDocumentationFile>true</GenerateDocumentationFile>` for the Swagger docs to work properly

**Comment by dansiegel** [comment]
we would need to add a XML docs on class and method which I'm not overly inclined to do in the template
