### ISSUE TITLE
`Packages_Validation SkiaOnlyHeads` CI logs shows Mobile and Wasm projects being built

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#39]
![image](https://user-images.githubusercontent.com/31348972/229363517-25050936-52cf-42ae-bf22-c009e0ae8434.png)

I think this CI job is supposed to be creating a Skia-only project. It's quite weird the logs are showing Mobile and Wasm projects.

**Comment by nickrandolph** [comment]
This has been fixed - the validation steps weren't creating apps using the correct argument (see https://github.com/unoplatform/uno.templates/pull/51/files#diff-86fc0ec71c5b4e45aca47615e4b44a589beac6423826de69fff0d2438629ab1fR60-R63)
