### ISSUE TITLE
Add the option of `Uno.CrossTargetting.targets`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#391]
## What would you like to be added:

Currently to make a given file target a specific platform only, it must be wrapped in `#if __SOMEPLATFORM__` statements. Instead, it would be great to provide the option to generate something akin to https://github.com/unoplatform/uno/blob/master/src/Uno.CrossTargetting.targets to automatically include source files based on their suffix. Skia and WASM would be targeted as `.crossruntime.cs`.

## Why is this needed:

UX

## For which Platform:

All

**Comment by Youssef1313** [comment]
Should this be provided by Uno itself?

**Comment by MartinZikmund** [comment]
@Youssef1313 It sounds like that could be a breaking change (theoretically), although whoever is already using these suffixes is probably using them for this purpose anyway

**Comment by jeromelaban** [comment]
I don't think the template should be providing too many of those opinionated project structure, We should explain users how to do it, but it's an explicit choice that developers will have to make.

It must not be in Uno itself, that's for certain.

**Comment by MartinZikmund** [comment]
I would say that it could still be an optional feature in Features section of the wizard - there is a lot of things the template already presets, so this does not sound too problematic, and sounds useful for many scenarios

**Comment by dansiegel** [comment]
Closing this issue as the CrossTargetting.targets are included by default in the Uno.Sdk
