### ISSUE TITLE
`App.cs` indentation is not correct

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#393]
## Current behavior

![image](https://github.com/unoplatform/uno.templates/assets/1075116/b845a96f-45ec-4a95-a9c3-9edefbf60385)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dansiegel** [comment]
@MartinZikmund can you confirm if the file is using Block or a file scoped namespace. I can replicate this issue in another part of the app where Visual Studio changed the file from file scoped to a block scoped namespace.

Looking at the template `MainWindow.EnableHotReload()` is properly indented so my thought is this is most likely something that Visual Studio is doing as it applies formatting to your project.

Another good test would be if you create a project from the command line do you get the same results?

**Comment by MartinZikmund** [comment]
Indeed it changed to block scoped because the version I had still included block scoped namespaces in editorconfig. The master version looks ok, so closing  👍 !
