### ISSUE TITLE
Template 4.8 .UseToolkitNavigation() not found

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno.templates#4]
### Current behavior

![image](https://user-images.githubusercontent.com/43340959/226855148-0c7149a1-69e8-4561-9965-a2c665be017f.png)

### How to reproduce it (as minimally and precisely as possible)

Just created a blank solution with the latest 4.8 template in Visual Studio 17.5.3 and selected Windows and Android only.

### Works on UWP/WinUI

None

### Affected platforms

Android, Windows

### IDE

Visual Studio 2022

### IDE version

17.5.3

**Comment by nickrandolph** [comment]
Fix: https://github.com/unoplatform/uno.templates/pull/23

**Comment by sigmarsson** [comment]
@nickrandolph which version will ship the fix  > 4.8.8.8 ?

**Comment by sigmarsson** [comment]
![image](https://user-images.githubusercontent.com/43340959/233582470-df5a182e-97f4-43c0-8166-be7deb9744c8.png)

<img width="706" alt="image" src="https://user-images.githubusercontent.com/43340959/233582758-1cdeb581-00e9-4b23-bd26-20348fe840a5.png">
