### ISSUE TITLE
Audit / Simplify MtouchExtraArgs for iOS & MacCatalyst targets

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno.templates#413]
## Description

Currently the Mobile head has several additions for the `MtouchExtraArgs`. MtouchExtraArgs are black magic to a lot of developers and not overly well documented. We should avoid having MtouchExtraArgs unless they are absolutely necessary. Especially considering that both of the extra MtouchExtraArgs that have a reference to an issue link to a closed issue these need to be updated. These should be updated as follows:

1) Removed if no longer needed for net7 and net8
2) Wrapped in a template condition if it is required for net7 but not for net8
3) Each argument should have a reference issue or description for why we are adding it

```xml
<!-- Configure the GC -->
<MtouchExtraArgs>$(MtouchExtraArgs) --setenv=MONO_GC_PARAMS=soft-heap-limit=512m,nursery-size=64m,evacuation-threshold=66,major=marksweep,concurrent-sweep</MtouchExtraArgs>

<!-- See https://github.com/unoplatform/uno/issues/9430 for more details. -->
<MtouchExtraArgs>$(MtouchExtraArgs) --registrar:static</MtouchExtraArgs>

<PropertyGroup Condition="'$(Configuration)'=='Release'">
  <!-- https://github.com/xamarin/xamarin-macios/issues/14812 -->
  <MtouchExtraArgs>$(MtouchExtraArgs) --marshal-objectivec-exceptions:disable</MtouchExtraArgs>
</PropertyGroup>
```

**Comment by jeromelaban** [comment]
Moved to the SDK
