### ISSUE TITLE
`solution-config.props.sample` should not mention Visual Studio

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#420]
Unless I am mistaken, `solution-config.props` does not apply to VS only, correct?

https://github.com/unoplatform/uno.templates/blob/414a74780cfb9766c9bbe4fdf1bb2c7274e14f18/src/Uno.Templates/content/unoapp/solution-config.props.sample#L3

**Comment by jeromelaban** [comment]
Visual Studio should be explicitly mentioned here, as it's only useful in Visual Studio. Other IDEs should not be using this.

**Comment by MartinZikmund** [comment]
@jeromelaban so when just .NET Android target is ran, VS Code and Rider will not compile the main class library for the other targets? My scenario is - I need to build a portion of code as platform-specific, but want to focus on a single platform first - e.g. I write a `SoundPlayerService.Android.cs`. The class library then won't build for the other targets, only .NET Android, because the references to `SoundPlayerService` will not resolve.

**Comment by nickrandolph** [comment]
VS Code won't build the class library for all targets, so this isn't an issue there
We need to understand whether Rider is similar to VS or VS Code behaviour
Regardless, it's pretty explicit that the intent of this file is to control the behaviour in VS.

**Comment by nickrandolph** [comment]
Code in template has been updated to make this all more explicit, so I'm going to close this issue
