### ISSUE TITLE
OnLaunched may fail when activated with a custom protocol

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.templates#457]
I just created an empty project using the lastest Uno wizard, and have noticed that some things have changed. It appears that the current window is always set to `null` when launched using [custom protocol activation](https://platform.uno/docs/articles/features/protocol-activation.html), and this produces a crash when calling the SetWindowIcon function. This used to work perfectly fine on older versions, where this new method simply wasn't being called :

![image](https://github.com/unoplatform/uno/assets/45963857/5a3c75e5-b95c-4029-83b8-bf2bac47526e)

New AppHead class : 
``` csharp 
using Microsoft.UI.Xaml;
using Uno.Resizetizer;

namespace MyProject
{
    public sealed partial class AppHead : App
    {
        /// <summary>
        /// Initializes the singleton application object. This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public AppHead()
        {
            this.InitializeComponent();
        }

        /// <summary>
        /// Invoked when the application is launched normally by the end user.  Other entry points
        /// will be used such as when the application is launched to open a specific file.
        /// </summary>
        /// <param name="args">Details about the launch request and process.</param>
        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
            base.OnLaunched(args);

            MainWindow.SetWindowIcon();
        }
    }
}
```

Older AppHead  class : 
``` csharp
using Microsoft.Extensions.Logging;
using Microsoft.UI.Xaml;
using System;

namespace MyProject
{
    public sealed partial class AppHead : App
    {
        static AppHead() =>
            InitializeLogging();

        /// <summary>
        /// Initializes the singleton application object. This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public AppHead()
        {
            this.InitializeComponent();
        }

        /// <summary>
        /// Configures global Uno Platform logging
        /// </summary>
        private static void InitializeLogging()
        {
#if DEBUG
		// Logging is disabled by default for release builds, as it incurs a significant
		// initialization cost from Microsoft.Extensions.Logging setup. If startup performance
		// is a concern for your application, keep this disabled. If you're running on the web or
		// desktop targets, you can use URL or command line parameters to enable it.
		//
		// For more performance documentation: https://platform.uno/docs/articles/Uno-UI-Performance.html

		var factory = LoggerFactory.Create(builder =>
		{
#if __WASM__
			builder.AddProvider(new global::Uno.Extensions.Logging.WebAssembly.WebAssemblyConsoleLoggerProvider());
#elif __IOS__ || __MACCATALYST__
			builder.AddProvider(new global::Uno.Extensions.Logging.OSLogLoggerProvider());
#elif NETFX_CORE
			builder.AddDebug();
#else
			builder.AddConsole();
#endif

			// Exclude logs below this level
			builder.SetMinimumLevel(LogLevel.Information);

			// Default filters for Uno Platform namespaces
			builder.AddFilter("Uno", LogLevel.Warning);
			builder.AddFilter("Windows", LogLevel.Warning);
			builder.AddFilter("Microsoft", LogLevel.Warning);

			// Generic Xaml events
			// builder.AddFilter("Microsoft.UI.Xaml", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.VisualStateGroup", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.StateTriggerBase", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.UIElement", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.FrameworkElement", LogLevel.Trace );

			// Layouter specific messages
			// builder.AddFilter("Microsoft.UI.Xaml.Controls", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.Controls.Layouter", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.Controls.Panel", LogLevel.Debug );

			// builder.AddFilter("Windows.Storage", LogLevel.Debug );

			// Binding related messages
			// builder.AddFilter("Microsoft.UI.Xaml.Data", LogLevel.Debug );
			// builder.AddFilter("Microsoft.UI.Xaml.Data", LogLevel.Debug );

			// Binder memory references tracking
			// builder.AddFilter("Uno.UI.DataBinding.BinderReferenceHolder", LogLevel.Debug );

			// RemoteControl and HotReload related
			// builder.AddFilter("Uno.UI.RemoteControl", LogLevel.Information);

			// Debug JS interop
			// builder.AddFilter("Uno.Foundation.WebAssemblyRuntime", LogLevel.Debug );
		});

		global::Uno.Extensions.LogExtensionPoint.AmbientLoggerFactory = factory;

#if HAS_UNO
		global::Uno.UI.Adapter.Microsoft.Extensions.Logging.LoggingAdapter.Initialize();
#endif
#endif
        }
    }
}
``` 
I tried simply commenting out the new method, but as you can imagine that just created other problems : 

![image](https://github.com/unoplatform/uno/assets/45963857/65ec353f-fa58-4c5a-b314-d8011cdd7ae0)

_Originally posted by @BertrandDeSaintBezier in https://github.com/unoplatform/uno/discussions/14005_

**Comment by dansiegel** [comment]
@BertrandDeSaintBezier can you provide:

1) What were the template options you had selected when you created the project?
2) What is the code of the OnLaunched in the App.cs?

The MainWindow should have been set in the App.cs in the shared multi-targeted library. 

```cs
// AppHead.xaml.cs
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
    base.OnLaunched(args);

    MainWindow.SetWindowIcon();
}
```

You'll notice that the MainWindow.SetWindowIcon() is called after `base.OnLaunched(args)` which should invoke what you have in the App.cs. So it's really in there that we need to see what's going on to identify why the MainWindow is null

**Comment by dansiegel** [comment]
@BertrandDeSaintBezier the output you have there for your App.cs isn't standard that we have in the template. But what I am noticing is that you have a condition that checks `mainInstance.IsCurrent is not true` where you return from there. When you get the error you reported is this condition true where you would be returning? It appears you only set MainWindow in your HostApplication method.

Keep in mind that if you return before that MainWindow will be null and then you'll end up in the AppHead's override trying to execute against a null Window.

**Comment by BertrandDeSaintBezier** [comment]
This code is used to handle the activation of the application from a redirect URI. It appears that when the application is opened from a redirect (such as when signing in using SSO, which opens a web page that redirects to the application), a new instance of Uno is opened instead of redirecting to the "current" instance. You can read more about this in this discussion : https://github.com/unoplatform/uno/discussions/12933 which references [this repo](https://github.com/andrewleader/RedirectActivationWinUI3Sample/blob/main/RedirectActivationWinUI3Sample/App.xaml.cs) by a PM @WinAppSDK.

Long story short, yes this code isn't standard, but by definition it can't be as I'm trying to handle a URI redirect 🥴

The issue at hand is the fact that while this exact code used to work in a previous version of Uno (I couldn't say which version for sure, but the project was created on the 1st of June 2023, running the latest .NET 7 version of Uno at the time), it doesn't any more in the latest Uno versions. Both projects are using the exact same templates (with the exception of .NET version, but I've tried using .NET 7 for both and the bug is the same). Somewhere along the line something changed. 

The only other clue I've got is the fact that in this older project, the `.Base` project isn't included in the solution but exists in the folder structure.
![image](https://github.com/unoplatform/uno.templates/assets/45963857/2ec57e7f-2478-4f52-9235-b1c64888b8be)

By contrast, the newer project has a folder structure that seems to have shifted somewhat
![image](https://github.com/unoplatform/uno.templates/assets/45963857/58de6066-1fbc-47f5-9444-8ba568b0fa56)

Whatever the case, in the older version, the AppHead's override was never a problem.

**Comment by dansiegel** [comment]
There isn't an issue with what you're doing. It just needs some subtle changes to work correctly. Here are 3 solutions off the top of my head that would work

1) You could simply set the MainWindow in your return block of your App.cs
```cs
if (mainInstance.IsCurrent is not true) {
    MainWindow = new Window();
    await mainInstance.RedirectActivationToAsync(activatedArgs);
    Process.GetCurrentProcess().Kill();
    return;
}
```

2) You could add the IsCurrent check in your AppHead.xaml.cs
```cs
var activatedArgs = AppInstance.GetCurrent().GetActivatedEventArgs();
var mainInstance = AppInstance.FindOrRegisterForKey("main");

if (mainInstance.IsCurrent is not true) {
    await mainInstance.RedirectActivationToAsync(activatedArgs);
    Process.GetCurrentProcess().Kill();
    return;
}

base.OnLaunched(args);

MainWindow.SetWindowIcon();
```

3) You could simply safeguard the MainWindow in the event it's null in your AppHead.xaml.cs
```cs
MainWindow?.SetWindowIcon();
```

Given that this isn't really an issue with the templates, and you have 3 ways to fix it here I'm going to close the issue. But if you continue to have issues please let us know.
