### ISSUE TITLE
```wizard``` point over disabled style

### ISSUE THREAD

**Issue by limeniye** [unoplatform/uno.templates#467]
This problem happens with **Regions**, **Logging Default**, **Logging Serilog**; **Authentication Custom**, **MSAL**, **OIDC**, **Web**
But doesn't happen with the **Configuration**, **HTTP**, **Localization**.

![UnoWizardDisabledPointOverStyle](https://github.com/unoplatform/uno/assets/69314237/ba17beec-a95d-4244-b4c3-e6e4627df294)

**Comment by jeromelaban** [comment]
Fixed
