### ISSUE TITLE
Error message when running dotnet new unoapp

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno.templates#484]
### Current behavior

When executing the command below, two errors appear.

```
dotnet new unoapp -o ProjectErrorVersion -preset="recommended" -id="com.companyname.ProjectErrorVersion" -pub="O=ProjectErrorVersion" -theme-service=true -theme="material" -presentation="mvux" -config=true -di=true -log="default" -nav="regions" -http=true -loc=true -server=true -tests=none -tests=unit -tests=ui -toolkit=true -dsp=true
```

Error Message 1

```
Solution file error MSB5023: Error parsing the nested project section "ProjectErrorVersion.Tests" in solution file. A project with the GUID "{5D214900-9983-4AE0-8BBD-F3F90F655FB9}" is listed as being nested under project "{6467782B-1F57-44AD-891E-522BE9311DA5}", but does not exist in the solution.
```

Erros Message 2

```
The PackageReference items FluentAssertions;Microsoft.NET.Test.Sdk;NUnit;NUnit3TestAdapter do not have corresponding PackageVersion.
```

But the project build and run.

### Expected behavior

That the command runs without showing errors.

### Template Host

dotnet new

### Host OS

Windows

### Template Options

dotnet new unoapp -o ProjectErrorVersion4 -preset="recommended" -id="com.companyname.ProjectErrorVersion" -pub="O=ProjectErrorVersion" -theme-service=true -theme="material" -presentation="mvux" -config=true -di=true -log="default" -nav="regions" -http=true -loc=true -server=true -tests=none -tests=unit -tests=ui -toolkit=true -dsp=true

### Template Version

```shell
Uno.Templates::5.0.36
```

### Anything else we need to know?

The command was generated using Uno.Studio.
Theoretically it would be recommended, removing what has default information in dotnetcli.host.json

**Comment by dansiegel** [comment]
It would appear that something has broken the logic around the computed symbol `useTestSolutionFolder` as all of the dependencies are missing for this and the folder is missing from the solution.

**Comment by dansiegel** [comment]
Actually taking a closer look at this the problem seems to be with the command itself. We have some limitations in checking choice parameters. The option `none` isn't meant to be used with either `ui` or `unit` for tests.
> -tests=none -tests=unit -tests=ui

**Comment by rafael-rosa-knowcode** [comment]
In the file Template.json the test allowMultipleValues.


![image](https://github.com/unoplatform/uno.templates/assets/116665025/743be2e3-b242-448b-afa8-2f302438957b)


And the default value for tests on the Recommended version was "none|unit|ui".

![image](https://github.com/unoplatform/uno.templates/assets/116665025/0a0b198e-534d-4558-a2a0-9fda5944bd0b)

Good observation. I missed this one.
Updated the default uno.studio file and it worked perfectly.


In my case it is resolved.
Should we handle this in the templates? If not for now, we can close the issue.

**Comment by dansiegel** [comment]
This isn't an issue for the defaults in the template
