### ISSUE TITLE
[Bug] Blank template includes Uno.Resizetizer

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno.templates#485]
### Current behavior

Blank template includes Uno.Resizetizer

### Expected behavior

Blank template does not include any "advance" feature

### Affected platforms

iOS, Android, MacCatalyst, WebAssembly, Gtk, Linux Framebuffer, Wpf, Windows (WinAppSdk)

### Template Host

Visual Studio

### Host OS

macOS, Windows, Linux

### Template Options

blank

### Template Version

```shell
5.0.17.30
```

**Comment by dansiegel** [comment]
I don't believe this is something that we want to change for any reason. The template should come with Resizetizer the same way that you get it by default with MAUI.
