### ISSUE TITLE
[Bug] dotnet publish for maccatalyst does not produce a fat app

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno.templates#487]
### Current behavior

Unlike MS SDK doing a `dotnet publish` for Mac Catalyst does not produce a fat (x64 + arm64) app bundle.

see https://github.com/unoplatform/uno/discussions/14660#discussioncomment-7789394

### Expected behavior

Uno's default should be identical to the MS SDK - if only to reduce the amount of contradicting documentation between the platforms.

### Affected platforms

MacCatalyst

### Template Host

dotnet new

### Host OS

macOS

### Template Options

maccatalyst

### Template Version

Latest templates (and `main`) have this issue.

Also note that the suggestion to run `dotnet new details Uno.Templates` does not do anything useful for me ?!?

```shell
$ dotnet new details Uno.Templates                                                                                                                   
No templates or subcommands found matching: 'details'.

To list installed templates similar to 'details', run:
   dotnet new list details
To search for the templates on NuGet.org, run:
   dotnet new search details


For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
```

### Anything else we need to know?

Recent SDK (iirc net7) changed the publish to fat (both x64 and arm64) and (again if my memory serve) the `dotnet build` is done for the current arch (it used to be hardcoded to `x64`).

Uno templates behave differently because `*.Mobile.csproj` includes this:

```xml
<RuntimeIdentifier Condition="'$(RuntimeIdentifier)'==''">maccatalyst-x64</RuntimeIdentifier>
```

which applies to both `build` (not optimal for developers using Apple Silicon Macs) and _incorrect_ when doing a `publish`.

**Comment by Youssef1313** [comment]
> Also note that the suggestion to run `dotnet new details Uno.Templates` does not do anything useful for me ?!?

`dotnet new details` is new in .NET 8, implemented in https://github.com/dotnet/sdk/pull/31743.
