### ISSUE TITLE
Default spacing in XAML/XML

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#544]
It _feels_ that the default formatting should use 4 spaces in XAML and XML files, as 2 feels a bit crammed:

2 spaces

![image](https://github.com/unoplatform/uno.templates/assets/1075116/1065980b-6976-4858-ab58-264ce8d460b3)

4 spaces

![image](https://github.com/unoplatform/uno.templates/assets/1075116/8c866756-a119-465b-b7e9-5d73db266a00)

Obviously a style choice, but we use the latter throughout Uno itself, and it might be easier to read

**Comment by dansiegel** [comment]
Eventually if the dotnet template team provides a mechanism to apply formatting changes it's something we could look at exposing as an option... but no matter what style choices we make someone will not be happy with it.

**Comment by jeromelaban** [comment]
I tend to think that we should use formatting for our own template formatting during CI or dev, but not include one in the generated solution, and leave the developer to follow what is needed.
