### ISSUE TITLE
global.json should be in the "Solution items"

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.templates#546]
To facilitate the edition of the `global.json` it should be in the "Solution items" section automatically.

**Comment by MartinZikmund** [comment]
Also we should include a comment on how to bump uno in `Directory.Packages.props`

**Comment by dansiegel** [comment]
it already is part of the solution items:
https://github.com/unoplatform/uno.templates/blob/61383f28d95e9491212f67b463a48f9a43b9cbc8/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.sln#L74
