### ISSUE TITLE
[Bug] Generated dotnet new command causes error

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.templates#550]
### Current behavior

I used the WASM Wizard to generate a `dotnet new unoapp` command and it resulted in the following error

> Error: Invalid option(s):
-cultures -theme-service, False
   '-theme-service, False' is not a valid value for -cultures. The possible values are:
      ar        - Arabic
      cs        - Czech
      da        - Danish
      de        - German
      es        - Spanish
      fr        - French
      it        - Italian
      ja        - Japanese
      ko        - Korean
      nl        - Dutch
      pt-BR     - Portuguese (Brazil)
      ru        - Russian
      sv        - Swedish
      tr        - Turkish
      uk        - Ukrainian
      vi        - Vietnamese
      zh-Hans   - Chinese (Simplified)
      zh-Hant   - Chinese (Traditional)

## Steps to repro:

1. Customize the Blank template
2. Go to Theme
3. Select Material
4. Select Theme Service
5. DESELECT THEME SERVICE
6. Create

The following command was generated:

`dotnet new unoapp -o NavBarApp -id "com.companyname.NavBarApp" -pub "O=NavBarApp" -cultures "" -theme-service False -skip  -theme "material" -presentation "none" -config false -di false -log "none" -nav "blank" -http false -loc false -server false -tests "none" -toolkit  -dsp false`

### Expected behavior

Template generates properly

### Template Host

dotnet new

### Host OS

Windows

### Template Options

dotnet new unoapp -o NavBarApp -id "com.companyname.NavBarApp" -pub "O=NavBarApp" -cultures "" -theme-service False -skip  -theme "material" -presentation "none" -config false -di false -log "none" -nav "blank" -http false -loc false -server false -tests "none" -toolkit  -dsp false

### Template Version

```shell
`dotnet new` Package version: 5.2.0-dev.75
```

**Comment by nickrandolph** [comment]
This is fixed in the wizard
