### ISSUE TITLE
Back button and three dots button in `NavigatorBar` are pixelated

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#57]
## Current behavior

It seems the buttons on `NavigationBar` is using some scaled up bitmap instead of vector font icon. It also seems a tad too large

![image](https://user-images.githubusercontent.com/1075116/230768771-e37531b6-fe85-4031-a14e-069df8f5926f.png)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
This appears to be fixed in the lates template
