### ISSUE TITLE
[Bug] Incorrect code from Wizard

### ISSUE THREAD

**Issue by pictos** [unoplatform/uno.templates#578]
### Current behavior

(Reported by a user on our [discord server](https://discord.com/channels/1182775715242967050/1193995186951426048/1209187680311574578))

When using the VS Wizard (5.1.22.24) with the following options:

> Android, iOS and windows and Then  mvvm. Xaml markup, and fluent theme with theme service enabled. Dependency injection, configuration, regions, default logging, toolkit, Maui embedding, central package management, msal authentication, unit en ui testen en Azure pipelines

The generated code, for the `App.OnLaunched` is missing the `host.UseSerialization()`  causing the app to crash during startup.
![image](https://github.com/unoplatform/uno.templates/assets/20712372/6d181bc5-ec5a-4797-9aab-09151981f181)

Also, the `MauiVersion` generated is `8.0.5` and that causes warnings and conflicts, it can be fixed by changing the value to `8.0.7`.

The log message for the `MauiVersion` issue is:

```
\repos\WizardUnoIssue\WizardUnoIssue\WizardUnoIssue.csproj : warning NU1603: WizardUnoIssue depends on Microsoft.Maui.Controls (>= 8.0.5) but Microsoft.Maui.Controls 8.0.5 was not found. An approximate best match of Microsoft.Maui.Controls 8.0.6 was resolved.
\repos\WizardUnoIssue\WizardUnoIssue\WizardUnoIssue.csproj : warning NU1603: WizardUnoIssue depends on Microsoft.Maui.Controls.Compatibility (>= 8.0.5) but Microsoft.Maui.Controls.Compatibility 8.0.5 was not found. An approximate best match of Microsoft.Maui.Controls.Compatibility 8.0.6 was resolved.
\repos\WizardUnoIssue\WizardUnoIssue\WizardUnoIssue.csproj : warning NU1603: WizardUnoIssue depends on Microsoft.Maui.Graphics (>= 8.0.5) but Microsoft.Maui.Graphics 8.0.5 was not found. An approximate best match of Microsoft.Maui.Graphics 8.0.6 was resolved.
\repos\WizardUnoIssue\WizardUnoIssue.MauiControls\WizardUnoIssue.MauiControls.csproj : warning NU1603: WizardUnoIssue.MauiControls depends on Microsoft.Maui.Controls (>= 8.0.5) but Microsoft.Maui.Controls 8.0.5 was not found. An approximate best match of Microsoft.Maui.Controls 8.0.6 was resolved.
\repos\WizardUnoIssue\WizardUnoIssue.MauiControls\WizardUnoIssue.MauiControls.csproj : warning NU1603: WizardUnoIssue.MauiControls depends on Microsoft.Maui.Controls.Compatibility (>= 8.0.5) but Microsoft.Maui.Controls.Compatibility 8.0.5 was not found. An approximate best match of Microsoft.Maui.Controls.Compatibility 8.0.6 was resolved.
``` 

### Expected behavior

The template adds the `host.UseSerialization()` call and uses a `MauiVersion` that doesn't cause conflicts.

### Template Host

Visual Studio

### Host OS

Windows

### Template Options

Android, iOS and windows and Then  mvvm. Xaml markup, and fluent theme with theme service enabled. Dependency injection, configuration, regions, default logging, toolkit, Maui embedding, central package management, msal authentication, unit en ui testen en Azure pipelines

### Template Version

```shell
5.1.22.24
```

**Comment by nickrandolph** [comment]
CLI command:
`dotnet new unoapp -o PictosTestApp -id "com.companyname.PictosTestApp" -pub "O=PictosTestApp" -platforms "android" -platforms "ios" -platforms "windows" -auth "msal" -theme-service  -ci "azure" -cpm  -vscode False -pwa False -maui  -theme "fluent" -presentation "mvvm" -config  -di  -log "default" -nav "regions" -http false -loc false -server false -tests "unit" -tests "ui" -toolkit  -dsp false`
