### ISSUE TITLE
[Bug] warning CS8604 Possible null reference

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno.templates#586]
### Current behavior

```
/Users/poupou/git/templates/uno/5.2.0-dev.130/unoapp/unoapp/App.cs(16,9): warning CS8604: Possible null reference argument for parameter 'window' in 'void WindowExtensions.EnableHotReload(Window window)'. [/Users/poupou/git/templates/uno/5.2.0-dev.130/unoapp/unoapp/unoapp.csproj]
```

because of

```csharp
#if NET6_0_OR_GREATER && WINDOWS && !HAS_UNO
        MainWindow = new Window();
#else
        MainWindow = Microsoft.UI.Xaml.Window.Current;
#endif

#if DEBUG
        MainWindow.EnableHotReload();
#endif
```

where `Current` is defined as `Window?`

### Expected behavior

No warning

### Affected platforms

iOS

### Template Host

dotnet new

### Host OS

macOS

### Template Options

dotnet new unoapp -o unoapp -id "com.companyname.unoapp" -pub "O=unoapp" -theme "fluent" -presentation "none" -config false -di false -log "none" -nav "blank" -http false -loc false -server false -tests "none" -toolkit false -dsp false

### Template Version

```shell
5.2.0-dev.130
```

**Comment by dansiegel** [comment]
This is fixed in #585
