### ISSUE TITLE
Localization does not seem to be working

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#62]
## Current behavior

On the main page there should be localized application name. Instead the string "ApplicationName" is showing up.

![image](https://user-images.githubusercontent.com/1075116/230769555-7c9c72b1-5f4d-434f-a9df-e7719106cfaf.png)

![image](https://user-images.githubusercontent.com/1075116/230769522-b7472571-ccd4-4232-9c9b-f27a121a83c7.png)

Tested on WASM and Windows, probably fails on other targets too.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
I'm going to close this as this has already been fixed in latest uno/extensions (see https://github.com/unoplatform/uno.extensions/issues/1307)
