### ISSUE TITLE
Files appsettings.*.json build action should be EmbeddedResource

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.templates#626]
### Current behavior

Files appsettings.json and appsettings.development.json are created with build action set to none. The files can't be read if not set to EmbeddedResource.

### Expected behavior

Files appsettings.json and appsettings.development.json build action should be EmbeddedResource.

### Template Host

dotnet new

### Host OS

Windows

### Template Options

Example:

```ps1
dotnet new unoapp -o Commerce -preset "recommended" -id "com.companyname.Commerce" -pub "O=Commerce" -theme-service  -theme "material" -presentation "mvux" -config  -di  -log "default" -nav "regions" -http  -loc  -server False -tests "none" -toolkit  -dsp
```

### Template Version

```shell
5.2.2
```

### Anything else we need to know?

Leads to https://github.com/unoplatform/uno.extensions/issues/2224.

**Comment by dansiegel** [comment]
Unable to reproduce. Fixed
