### ISSUE TITLE
`TargetFrameworks` should be better as a single line

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#654]
![image](https://github.com/unoplatform/uno.templates/assets/31348972/d3791071-c539-4a70-bb5c-e7179221a425)

**If** someone decided to do `<CompilerVisibleProperty Include="TargetFrameworks" />` for some reason, the multi-line will break Roslyn. The way compiler-visible properties are passed to the compiler is by generating an .editorconfig file. But Roslyn will not handle this case properly (known limitation).

**NOTE:** I know it's not common at all that someone makes `TargetFrameworks` a compiler-visible property (usually people would care about `TargetFramework`). But if someone decided to do it. It will break badly.

**Comment by jeromelaban** [comment]
I agree. It's causing more trouble than the readability it improves.

**Comment by eriklimakc** [comment]
Does this mean updating all the samples migrated and in migration process to use single line tfms?

cc @agneszitte @jeromelaban

**Comment by dansiegel** [comment]
@eriklimakc yes it would be good to update the samples to use a single line for the tfms
