### ISSUE TITLE
Delete commented out code in csproj

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#71]
https://github.com/unoplatform/uno.templates/blob/451295114871d1d06e40678be17990b78544ad22/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj#L179-L192

https://github.com/unoplatform/uno.templates/blob/451295114871d1d06e40678be17990b78544ad22/src/Uno.Templates/content/unoapp/MyExtensionsApp.1/MyExtensionsApp.1.csproj#L183-L196

**Comment by dansiegel** [comment]
Duplicate of #72. This is there intentionally. We do not want to remove this.
