### ISSUE TITLE
[Bug] Remove ExtensionsCore from the generated template

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.templates#715]
### Current behavior

The current creates a configuration with `ExtensionsCore`.

### Expected behavior

It should be removed or renamed when used.

### Affected platforms

iOS, Android, MacCatalyst, WebAssembly, Skia, Windows (WinAppSdk), Server

### Template Host

dotnet new

### Host OS

Windows

### Template Options

recommended

### Template Version

```shell
5.3-dev
```

**Comment by dansiegel** [comment]
This should have been fixed in #667
ExtensionsCore is not used in the template currently. Perhaps the issue is that it was never backported.

**Comment by jeromelaban** [comment]
That's probably the case, let's close then.
