### ISSUE TITLE
Should templates have `WindowsSdkPackageVersion`?

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#72]
See https://github.com/unoplatform/uno/issues/9450

The `<FrameworkReference Update...` code is no longer included in templates now (it's currently commented out and https://github.com/unoplatform/uno.templates/issues/71 tracks deleting it). But it wasn't replaced by `WindowsSdkPackageVersion`. Do we need it?

**Comment by dansiegel** [comment]
This is commented out specifically to ensure that it is easier for people should they encounter an error they can simply uncomment it. 
cc: @nickrandolph

**Comment by Youssef1313** [comment]
@dansiegel The `<FrameworkReference Update` thing is *said* to be deprecated and is documented as breaking change https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/override-windows-sdk-package-version#previous-behavior.

So we really need to either delete this commented code **or** replace it with a commented out `WindowsSdkPackageVersion`.

**Comment by dansiegel** [comment]
It would seem reasonable that if FrameworkReference is deprecated that we should look at an update to how this case is handled. 
cc: @jeromelaban @nickrandolph

**Comment by jeromelaban** [comment]
The block is still needed in some form, as the error message is still very obscure. As `WindowsSdkPackageVersion` is the newer way to fix it, let's do it.
