### ISSUE TITLE
[Bug] Invalid JSON (comment) in global.json shows up as error

### ISSUE THREAD

**Issue by spouliot** [unoplatform/uno.templates#767]
### Current behavior

The `global.json` file used for templates is **NOT** valid JSON - since comments are not allowed in the format.

While this works in practice it's not 

This makes VSCode always shows an error inside the file (filename is in red in the file explorer).

You can also see this inside the github editor itself

```json
{
  // To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.
  "msbuild-sdks": {
    "Uno.Sdk": "$UnoSdkVersion$"
  }
}
```

[link](https://github.com/unoplatform/uno.templates/blob/main/src/Uno.Templates/content/unoapp/global.json#L2)

### Expected behavior

To avoid tooling errors we need to use JSON-valid _pseudo comments_ like

```json
{
  "msbuild-sdks": {
    "//": "To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.",
    "Uno.Sdk": "5.2.0-dev.2103"
  }
}
```

That makes both Github and VS Code happier.

### Template Host

dotnet new

### Host OS

macOS

### Template Options

Anything that produce a Uno app project with the `global.json` file.

### Template Version

```shell
This is still the case with the git version.
```

**Comment by jojorne** [comment]
Does the parser not support jsonc? Also there are other places using jsonc.
https://code.visualstudio.com/docs/languages/json#_json-with-comments

**Comment by jeromelaban** [comment]
@jojorne interesting finding, that would be an interesting change indeed.
