### ISSUE TITLE
option to create solution with indent_style=tab

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.templates#777]
## What would you like to be added:
^title, for cs and xaml files

## Why is this needed:
general QOL without having to edit .editorconfig every time a new solution is created

**Comment by dansiegel** [comment]
While we would like to respect the developers preferences there is no way currently for us to reformat the project based on the users preferences. Perhaps in the future the .NET Team will solve this problem but for the time being this isn't something that we will be modifying.

**Comment by Xiaoy312** [comment]
im fine with the source files themselves, since it is just a matter of ctrl+e,d or r-click>format xaml.
but, is there nothing that cant be done for the .editorconfig?
we could have two versions and the chosen one gets to be copied.
